#!/usr/bin/env bash

vagrant_maybe_halt() {
	# Test if VVV is running, This is hardcoded with a VVV default site, and should be switched to something a bit more robust
	vvv_running="true"
	 curl --silent --head "http://local.wordpress.dev/wp-login.php" | head -n 1 | grep "HTTP/1.[01] [23].." > /dev/null || vvv_running="false"
	if [[ "$vvv_running" = "true" ]]; then
		info "Running \`vagrant halt\`"
		vagrant halt
	else
		info "Vagrant not running, skipping \`vagrant halt\`..."
	fi
}
