#!/usr/bin/env bash

run_vagrant_up() {
	# vagrant waaaaay up
	# =============================================================================
	cd "$path" || error "Could not change directory."
	if [[ "$skip_restart" = "false" ]]; then
		info "Running vagrant up --provision... "
		hook "pre_vagrant_provision"
		vagrant up --provision
		hook "post_vagrant_provision"
	fi
}

vagrant_maybe_halt() {
	# Test if VVV is running, This is hardcoded with a VVV default site, and should be switched to something a bit more robust
	vvv_running="true"
	/usr/bin/wget "http://local.wordpress.dev/wp-login.php" --timeout 5 -O - 2>/dev/null  | grep "login" || vvv_running="false"
	echo $vvv_running
	if [[ "$vvv_running" = "true" ]]; then
		info "Running \`vagrant halt\`"
		vagrant halt
	else
		info "Vagrant not running, skipping \`vagrant halt\`..."
	fi
}
