#!/usr/bin/env bash

_vv_zsh () {
  local curcontext="$curcontext" state line
  typeset -A opt_args
  _arguments \
    '1: :->command'

  case $state in
    command)
      compadd $(vv x show_commands)
      ;;
esac
}

if [ -n "$ZSH_VERSION" ]; then
  compdef _vv_zsh vv
elif [ -n "$BASH_VERSION" ]; then
   _vv()
   {
     _vv_commands=$(vv x show_commands)

     local cur prev
     COMPREPLY=()
     cur="${COMP_WORDS[COMP_CWORD]}"
     COMPREPLY=( $(compgen -W "${_vv_commands}" -- ${cur}) )

     return 0
   }
   complete -o nospace -F _vv vv

else
   echo "vv doesn't support completions in your shell yet."
fi
