#!/usr/bin/env bash

check_for_config_file() {
	hook "pre_vv_config_check"
	test -f "$HOME"/.vv-config && vv_config="${HOME}/.vv-config"
	test -f ./.vv-config && vv_config="./.vv-config"

	if [ ! -z $vv_config ]; then
		load_config_values
	else
		if [[ ! $showing_help = "true" ]]; then
			info "	"
			info "Looks like it's your first time running ${magenta}vv${normal}. "
			info "${magenta}vv${normal} couldn't find a config file, so we will create one now."
			info "This step only needs to be done once."
			info "	"
			get_vvv_path
		fi
	fi
	hook "post_vv_config_check"
}
