#!/usr/bin/env bash

check_for_update() {
	hook "pre_update_check"
	if [[ ! -z $(which curl) ]]; then
		hook "pre_github_update_check"
		github_version=$(curl -s https://api.github.com/repos/bradp/vv/tags | grep --color=never "\"name\": \"" | head -n 1 | sed 's/"name": "//' | sed 's/",//' | sed 's/ //g' )
		hook "post_github_update_check"
		if [[ ! -z "$github_version" ]]; then
			if [[ ! "$version_number" = "$github_version" ]]; then
				hook "pre_out_of_date_vv"
				info "Your version of vv ( $version_number )  does not match the current Github version ( $github_version ). Please update with vv --update"
				hook "post_out_of_date_vv"
			fi
		fi
	fi
	hook "post_update_check"
}
