#!/usr/bin/env bash

deployment_setup() {
	deployment_setup_prompt
	info "Setting up (S)FTP deployment for $site"

	while [ -z "$deployment_name" ]; do
		prompt "Name of deployment (production, staging, other, etc) "
		read -r deployment_name
	done

	while [ -z "$host" ]; do
		prompt "Host (if SFTP, define port as host:port) "
		read -r host
	done

	while [ -z "$username" ]; do
		prompt "FTP Username "
		read -r username
	done

	while [ -z "$password" ]; do
		prompt "FTP Password "
		read -r password
	done

	if [ -z "$passive" ]; then
		prompt "Use Passive transfer mode? (Y/n) "
		read -r passive
	fi
	if [[ "$passive" = "n" ]]; then
		passive="false"
	else
		passive="true"
	fi

	while [ -z "$secure" ]; do
		prompt "Use SFTP? (y/N)"
		read -r secure
	done
	if [[ "$secure" = "y" ]]; then
		secure="true"
	else
		secure="false"
	fi

	while [ -z "$destination" ]; do
		prompt "Destination path ( You probably want / or ~/public_html )"
		read -r destination
	done

	info "Setting up a deployment in your VVV Vagrantfile with the following information: "
	echo "	Site: $site"
	echo "	Deployment name: $deployment_name"
	echo "	Host: $host"
	echo "	Username: $username"
	echo "	Password: $password"
	echo "	Passive Mode: $passive"
	echo "	Secure Mode: $secure"
	echo "	destination: $destination"
	cp "$path/Vagrantfile" "$path/Vagrantfile-backup"

	vagrant_file=$(sed  '$ d' < "$path/Vagrantfile")
	echo "$vagrant_file" > "$path/Vagrantfile"
{
	echo "# begin-vv-$site-$deployment_name"
	echo "	config.push.define \"$site-$deployment_name\", strategy: \"ftp\" do |push|"
	echo "		push.host =\"$host\""
	echo "		push.username =\"$username\""
	echo "		push.password =\"$password\""
	echo "		push.passive =\"$passive\""
	echo "		push.secure =\"$secure\""
	echo "		push.destination =\"$destination\""
	echo "		push.dir = \"$path/$sites_folder/$site/htdocs\""
	echo "		push.exclude = \"wp-config.php\""
	echo "	end"
	echo "# end-vv-$site-$deployment_name"
} >> "$path/Vagrantfile"
	echo "end" >> "$path/Vagrantfile"
	success "Deployment setup finished. You can now deploy with a 'vv -v push $site-$deployment_name'"
}
