#!/usr/bin/env bash

deployment_setup_prompt() {
	info "Setting up a deployment."

	if [[ ! -z $site ]]; then
		not_valid_site
	fi

	# Get site dir name if not supplied as argument
	while [ -z "$site" ]; do
		prompt "Which site would you like to setup a deployment for? "
		read -r site
		not_valid_site
	done

}
